FROM base:ngc_cuda12.1_l11n

ENV UV_INSTALL_DIR="/opt/uv" \
    UV_PYTHON_INSTALL_DIR="/opt/uv/python" \
    UV_CACHE_DIR="/opt/uv/cache" \
    UV_DEFAULT_INDEX="https://mirrors.sustech.edu.cn/pypi/web/simple" \
    UV_TORCH_BACKEND="cu121" \
    UV_NO_BUILD_ISOLATION=1 \
    PATH="/opt/python3/bin:/opt/uv:$PATH"

RUN --mount=type=cache,target=/opt/uv/cache \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    uv venv /opt/python3 --python 3.10 && \
    uv pip install setuptools wheel ninja && \
    uv pip install torch torchvision torchaudio && \
    uv pip install boto3 datasets einops flash-attn fvcore hydra-colorlog hydra-core hydra-optuna-sweeper ipdb mamba-ssm monai neptune nibabel opencv-python openpyxl pre-commit pytorch_lightning rootutils seaborn thop timm torchsummary "transformers<5" vllm wandb
